[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
elementals = "AfFGKj5Wxm9FY4ZKZZMYxKRbx7zNYYKMmEUxnLfme2CX"

[programs.devnet]
elementals = "AfFGKj5Wxm9FY4ZKZZMYxKRbx7zNYYKMmEUxnLfme2CX"


[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts --verbose"
