[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
elementals = "4spD8zfoTFJDDbijBSgxxB8JsXfLx1jSBGx9K73hBgJz"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
